### ISSUE TITLE
No module named 'utils.collections'

### ISSUE THREAD

**Issue by seekingup** [NVIDIA/ContrastiveLosses4VRD#15]
Thanks for your code!
when I tried to do evaluation on Visual Genome using the command in README.md, there's a import error.
Traceback (most recent call last):
  File "./tools/test_net_rel.py", line 18, in <module>
    from core.config import cfg, merge_cfg_from_file, merge_cfg_from_list, assert_and_infer_cfg
  File "/home/seekingup/code/reldn/lib/core/config.py", line 29, in <module>
    from utils.collections import AttrDict
ModuleNotFoundError: No module named 'utils.collections'

It seems the 'utils' should only be in Detectron_pytorch, but here in lib.core.config, how can I fix it?

**Comment by seekingup** [comment]
I'm using pytorch1_0 branch.

**Comment by gitzyong812** [comment]
have you solved this problem? Thanks

**Comment by shabnamsadegh** [comment]
probably there is problem with installing(make) detectron. It is not the best solution but my problem solved when added detectron/lib to PATH.
