### ISSUE TITLE
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.

### ISSUE THREAD

**Issue by fuyun1107** [NVIDIA/ContrastiveLosses4VRD#30]
> Traceback (most recent call last):
  File "build.py", line 4, in <module>
    from torch.utils.ffi import create_extension
  File "/home/ubuntu/anaconda3/envs/xx/lib/python3.5/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.

why i have this problem?

**Comment by YerongLi2** [comment]
I met exactly the same problem, how did you fix this?
