### ISSUE TITLE
sg_dataset.zip can't be downloaded

### ISSUE THREAD

**Issue by TungWg** [NVIDIA/ContrastiveLosses4VRD#32]
sg_dataset.zip can't be downloaded, is there any other way to download it?

**Comment by fufangyu1206** [comment]
hi,you mean vg_dataset?

**Comment by becxer** [comment]
Where can I get vrd dataset images? original url is forbidden!

**Comment by lx10030802** [comment]
https://github.com/mohammadrezashariat/VSimplE
